#  G-CinemaPro | Streaming Management System

¡Bienvenido a **G-CinemaPro**! Un sistema de gestión de streaming de alto rendimiento desarrollado íntegramente en **Go**.

## 🛠️ Especificaciones Técnicas
- **Lenguaje:** Go (Golang)
- **Paradigma:** Funcional y Concurrente
- **Estructuras:** Slices dinámicos y Mapas (Hash Tables)

## 📂 Estructura del Proyecto
- `/docs`: Documentación y PDF de Planeación.
- `/cmd`: Punto de acceso al sistema (main.go).
- `/internal`: Lógica de negocio y modelos de datos.

## 🚀 Próximos Pasos
- [x] Planeación del software (Etapa 1)
- [ ] Desarrollo de modelos de datos
- [ ] Implementación de concurrencia
